name: linter-and-prettier
run-name: Push/PR created by @${{ github.actor }}
on: [push, pull_request]
jobs:
  code-integrity-verification:
    name: Code integrity verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Install dependencies
        run: NODE_ENV=development npm install

      - name: Check code style
        run: npm run format:check

      - name: Check code rules
        run: npm run lint:check
